### ISSUE TITLE
cached kb removal

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PublicKB#713]
https://www.ctl.io/knowledge-base/network/june-2014-bandwidth-model-change-faq/

if you search for 'bandwidth' this kb shows up but its been removed on purpose from our system due to being outdated.  we need to get it out of cache/search

**Comment by rpdubose** [comment]
I added a 301.  @chrislittle when we remove kb's we need to create a 301 otherwise they will still show up in search.  We use Google CSE for search which relies on the google index.  While there is a way to exclude a specific url from CSE, it only fixes part of the problem.  Now it will be excluded (can take up to 24 hrs) & if someone does still find the url, https://www.ctl.io/knowledge-base/network/june-2014-bandwidth-model-change-faq/ will be redirected to https://www.ctl.io/knowledge-base/network/.
